---
downloads: ~/Downloads/ansible

configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/galderz/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/0/dotfiles
#dotfiles_files:
#  - .bash_profile
#  - .gitignore
#  - .inputrc
#  - .osx
#  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
#  - autoconf
#  - bash-completion
#  - doxygen
#  - gettext
#  - gifsicle
  - bash
  - emacs-plus
  - homebrew/emacs/magit
  - git
  - gpg
  - haskell-stack
  - nvm
#  - go
#  - hub
#  - httpie
#  - iperf
#  - libevent
#  - sqlite
#  - mcrypt
#  - nmap
#  - node
#  - php
#  - ssh-copy-id
#  - cowsay
#  - readline
#  - openssl
#  - pv
  - unrar
  - wget
#  - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - d12frosted/emacs-plus

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - brave
  - docker
  - dropbox
  - firefox
  - gas-mask
  - google-chrome
  - intellij-idea
  - istat-menus
  - iterm2
  - skype
  - tunnelblick
  - virtualbox
  - vlc
  - xld

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
